### ISSUE TITLE
ThinkAny

### ISSUE THREAD

**Issue by BrunoGeorgevich** [felladrin/awesome-ai-web-search#5]
### Is your feature request related to a problem? Please describe.

Official website: https://thinkany.ai/

Launch date: I don't know. Maybe July 2024.

### Describe the solution you'd like

Platform: Web

![image](https://github.com/user-attachments/assets/d3b0a16d-72cb-46f3-a82e-bc7ce4608798)

**Comment by felladrin** [comment]
Perfect! Will add it! And here's the release date: 2024-03-22 [[Source](https://x.com/thinkanyai/status/1771073443271766193)]
