### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by BrunoGeorgevich** [felladrin/awesome-ai-web-search#6]
The ChatGPT is now able to search on the web.

Official website: https://www.chatgpt.com

Initial commit: [2023-10-31](https://openai.com/index/introducing-chatgpt-search/)

Platform: Web

Source code: Closed source

![image](https://github.com/user-attachments/assets/91390ae3-ca4d-4f82-9052-46514eb0f57b)

**Comment by felladrin** [comment]
Boa!
